const db = require('../database/db');
const { generateCard } = require('./cardGenerator');
const { validateBingo } = require('./bingoValidator');
const { assertTransition } = require('./stateMachine');
const { STATES, TX_TYPES } = require('../utils/constants');
const { atomicBalanceChange } = require('../database/queries/wallet');
const { fromCents } = require('../utils/helpers');
const logger = require('../utils/logger');
class BingoEngine {
  constructor(io, config){ this.io=io; this.config=config; this.timer=null; this.countdownTimer=null; this.state=STATES.WAITING; this.round=null; this.called=[]; this.ballBag=[]; }
  async init(){ await this.restore(); if(!this.round) await this.createRound(); this.schedule(); }
  serialize(){ return { state:this.state, round:this.round, calledNumbers:this.called, currentBall:this.called.at(-1)||null, prizePool:fromCents(this.round?.prize_pool_cents||0), countdownEndsAt:this.round?.next_action_at||null }; }
  emitState(){ this.io.emit('currentState', this.serialize()); }
  async restore(){ const live = await db.get('SELECT * FROM live_game WHERE id=1'); if(live?.active_round_id){ this.round = await db.get('SELECT * FROM game_rounds WHERE id=?',[live.active_round_id]); if(this.round){ this.state=this.round.state; this.called=JSON.parse(this.round.called_numbers||'[]'); this.ballBag=JSON.parse(this.round.ball_bag||'[]'); logger.info('Recovered round', this.round.round_code, this.state); } } }
  async createRound(){ const bag=Array.from({length:75},(_,i)=>i+1).sort(()=>Math.random()-0.5); const code=`R${Date.now().toString(36).toUpperCase()}`; const cardPrice=Math.round(Number(this.config.cardPrice)*100); const res=await db.run('INSERT INTO game_rounds(round_code,state,ball_bag,card_price_cents,next_action_at) VALUES(?,?,?,?,datetime(CURRENT_TIMESTAMP, ?))',[code,STATES.WAITING,JSON.stringify(bag),cardPrice,`+${this.config.countdownSeconds} seconds`]); this.round=await db.get('SELECT * FROM game_rounds WHERE id=?',[res.lastID]); this.state=STATES.WAITING; this.called=[]; this.ballBag=bag; await db.run('UPDATE live_game SET active_round_id=?, state=?, called_numbers=?, updated_at=CURRENT_TIMESTAMP WHERE id=1',[this.round.id,this.state,'[]']); this.emitState(); }
  async transition(to, extra={}){ assertTransition(this.state,to); this.state=to; const cols=['state=?']; const params=[to]; Object.entries(extra).forEach(([k,v])=>{ cols.push(`${k}=?`); params.push(v); }); params.push(this.round.id); await db.run(`UPDATE game_rounds SET ${cols.join(', ')} WHERE id=?`, params); this.round=await db.get('SELECT * FROM game_rounds WHERE id=?',[this.round.id]); await db.run('UPDATE live_game SET state=?, called_numbers=?, countdown_ends_at=?, updated_at=CURRENT_TIMESTAMP WHERE id=1',[to,JSON.stringify(this.called),this.round.next_action_at||null]); this.io.emit('syncState', this.serialize()); }
  schedule(){ this.clearTimers(); if(this.state===STATES.WAITING) this.countdownTimer=setTimeout(()=>this.startCountdown().catch(e=>logger.error(e)), 1500); if(this.state===STATES.COUNTDOWN) this.countdownLoop(); if(this.state===STATES.RUNNING) this.timer=setInterval(()=>this.draw().catch(e=>logger.error(e)), this.config.drawIntervalSeconds*1000); }
  clearTimers(){ if(this.timer) clearInterval(this.timer); if(this.countdownTimer) clearTimeout(this.countdownTimer); this.timer=null; this.countdownTimer=null; }
  async startCountdown(){ const ends=new Date(Date.now()+this.config.countdownSeconds*1000).toISOString(); await this.transition(STATES.COUNTDOWN,{next_action_at:ends}); this.countdownLoop(); }
  countdownLoop(){ const tick=async()=>{ const left=Math.max(0, Math.ceil((new Date(this.round.next_action_at).getTime()-Date.now())/1000)); this.io.emit('countdown',{seconds:left, endsAt:this.round.next_action_at}); if(left<=0){ await this.startRunning(); } else { this.countdownTimer=setTimeout(()=>tick().catch(e=>logger.error(e)),1000); } }; tick().catch(e=>logger.error(e)); }
  async startRunning(){ this.clearTimers(); await this.transition(STATES.RUNNING,{started_at:new Date().toISOString()}); this.io.emit('gameStarted', this.serialize()); this.timer=setInterval(()=>this.draw().catch(e=>logger.error(e)), this.config.drawIntervalSeconds*1000); }
  async draw(){ if(this.state!==STATES.RUNNING) return; if(this.ballBag.length===0){ await this.finish(null,null); return; } const ball=this.ballBag.shift(); this.called.push(ball); await db.run('UPDATE game_rounds SET called_numbers=?, ball_bag=? WHERE id=?',[JSON.stringify(this.called),JSON.stringify(this.ballBag),this.round.id]); await db.run('UPDATE live_game SET called_numbers=?, updated_at=CURRENT_TIMESTAMP WHERE id=1',[JSON.stringify(this.called)]); this.io.emit('numberCalled',{number:ball, calledNumbers:this.called, state:this.serialize()}); }
  async buyCard(userId){ if(![STATES.WAITING,STATES.COUNTDOWN].includes(this.state)) throw new Error('Card sales closed'); const card=generateCard(); const price=this.round.card_price_cents; await atomicBalanceChange(userId, TX_TYPES.CARD_PURCHASE, -price, `card:${this.round.id}:${userId}:${Date.now()}`, {roundId:this.round.id}); const res=await db.run('INSERT INTO bingo_cards(round_id,user_id,card_json) VALUES(?,?,?)',[this.round.id,userId,JSON.stringify(card)]); await db.run('UPDATE game_rounds SET prize_pool_cents=prize_pool_cents+? WHERE id=?',[price,this.round.id]); this.round=await db.get('SELECT * FROM game_rounds WHERE id=?',[this.round.id]); return { id:res.lastID, card, prizePool:fromCents(this.round.prize_pool_cents) }; }
  async claim(userId, cardId){ if(this.state!==STATES.RUNNING) throw new Error('Round not running'); const cardRow=await db.get('SELECT * FROM bingo_cards WHERE id=? AND user_id=? AND round_id=? AND active=1',[cardId,userId,this.round.id]); if(!cardRow) throw new Error('Card not found'); const result=validateBingo(JSON.parse(cardRow.card_json), this.called); if(!result.valid) return {valid:false, reason:'No authoritative Bingo pattern'}; await this.finish(userId, cardId); return {valid:true, pattern:result.pattern}; }
  async finish(winnerUserId, cardId){ if(this.state!==STATES.RUNNING) return; this.clearTimers(); await this.transition(STATES.FINISHED,{finished_at:new Date().toISOString(), winner_user_id:winnerUserId, winning_card_id:cardId}); this.io.emit('gameFinished', this.serialize()); await this.payout(winnerUserId); }
  async payout(winnerUserId){ await this.transition(STATES.PAYOUT); if(winnerUserId){ const payout=Math.floor(this.round.prize_pool_cents * this.config.payoutPercent); if(payout>0){ await atomicBalanceChange(winnerUserId, TX_TYPES.PAYOUT, payout, `payout:${this.round.id}`, {roundId:this.round.id}); await db.run('INSERT INTO leaderboard(user_id,wins,total_won_cents) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET wins=wins+1,total_won_cents=total_won_cents+excluded.total_won_cents,updated_at=CURRENT_TIMESTAMP',[winnerUserId,1,payout]); const user=await db.get('SELECT username,first_name FROM users WHERE id=?',[winnerUserId]); this.io.emit('bingoWinner',{userId:winnerUserId,name:user?.username||user?.first_name||'Player',amount:fromCents(payout)}); } }
    await this.transition(STATES.NEXT_ROUND); setTimeout(async()=>{ await this.transition(STATES.WAITING); await this.createRound(); this.schedule(); }, 3500); }
}
module.exports = { BingoEngine };
